/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as AuthorsProfileIdRouteImport } from './routes/authors/$profileId'
import { Route as PatentsIndexRouteImport } from './routes/patents/index'
import { Route as PatentsPatentIdRouteImport } from './routes/patents/$patentId'
import { Route as PublicationsIndexRouteImport } from './routes/publications/index'
import { Route as PublicationsPublicationIdRouteImport } from './routes/publications/$publicationId'
import { Route as AppDepartmentsCreateRouteImport } from './routes/app/departments/create'
import { Route as AppFacultiesCreateRouteImport } from './routes/app/faculties/create'
import { Route as AppImportsIndexRouteImport } from './routes/app/imports/index'
import { Route as AppPatentsIndexRouteImport } from './routes/app/patents/index'
import { Route as AppPatentsPatentIdRouteImport } from './routes/app/patents/$patentId'
import { Route as AppPatentsCreateRouteImport } from './routes/app/patents/create'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppProfileCreateRouteImport } from './routes/app/profile/create'
import { Route as AppProfileEditRouteImport } from './routes/app/profile/edit'
import { Route as AppPublicationsIndexRouteImport } from './routes/app/publications/index'
import { Route as AppPublicationsPublicationIdRouteImport } from './routes/app/publications/$publicationId'
import { Route as AppPublicationsCreateRouteImport } from './routes/app/publications/create'
import { Route as AppPatentsPatentIdEditRouteImport } from './routes/app/patents/$patentId/edit'
import { Route as AppPublicationsPublicationIdEditRouteImport } from './routes/app/publications/$publicationId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsProfileIdRoute = AuthorsProfileIdRouteImport.update({
  id: '/authors/$profileId',
  path: '/authors/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentsIndexRoute = PatentsIndexRouteImport.update({
  id: '/patents/',
  path: '/patents/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentsPatentIdRoute = PatentsPatentIdRouteImport.update({
  id: '/patents/$patentId',
  path: '/patents/$patentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsPublicationIdRoute =
  PublicationsPublicationIdRouteImport.update({
    id: '/publications/$publicationId',
    path: '/publications/$publicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppDepartmentsCreateRoute = AppDepartmentsCreateRouteImport.update({
  id: '/departments/create',
  path: '/departments/create',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultiesCreateRoute = AppFacultiesCreateRouteImport.update({
  id: '/faculties/create',
  path: '/faculties/create',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsIndexRoute = AppImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatentsIndexRoute = AppPatentsIndexRouteImport.update({
  id: '/patents/',
  path: '/patents/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatentsPatentIdRoute = AppPatentsPatentIdRouteImport.update({
  id: '/patents/$patentId',
  path: '/patents/$patentId',
  getParentRoute: () => AppRoute,
} as any)
const AppPatentsCreateRoute = AppPatentsCreateRouteImport.update({
  id: '/patents/create',
  path: '/patents/create',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileCreateRoute = AppProfileCreateRouteImport.update({
  id: '/profile/create',
  path: '/profile/create',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicationsIndexRoute = AppPublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicationsPublicationIdRoute =
  AppPublicationsPublicationIdRouteImport.update({
    id: '/publications/$publicationId',
    path: '/publications/$publicationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPublicationsCreateRoute = AppPublicationsCreateRouteImport.update({
  id: '/publications/create',
  path: '/publications/create',
  getParentRoute: () => AppRoute,
} as any)
const AppPatentsPatentIdEditRoute = AppPatentsPatentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppPatentsPatentIdRoute,
} as any)
const AppPublicationsPublicationIdEditRoute =
  AppPublicationsPublicationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppPublicationsPublicationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$profileId': typeof AuthorsProfileIdRoute
  '/patents/$patentId': typeof PatentsPatentIdRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/app/': typeof AppIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/patents/': typeof PatentsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/app/departments/create': typeof AppDepartmentsCreateRoute
  '/app/faculties/create': typeof AppFacultiesCreateRoute
  '/app/patents/$patentId': typeof AppPatentsPatentIdRouteWithChildren
  '/app/patents/create': typeof AppPatentsCreateRoute
  '/app/profile/create': typeof AppProfileCreateRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/publications/$publicationId': typeof AppPublicationsPublicationIdRouteWithChildren
  '/app/publications/create': typeof AppPublicationsCreateRoute
  '/app/imports/': typeof AppImportsIndexRoute
  '/app/patents/': typeof AppPatentsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/publications/': typeof AppPublicationsIndexRoute
  '/app/patents/$patentId/edit': typeof AppPatentsPatentIdEditRoute
  '/app/publications/$publicationId/edit': typeof AppPublicationsPublicationIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$profileId': typeof AuthorsProfileIdRoute
  '/patents/$patentId': typeof PatentsPatentIdRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/app': typeof AppIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/patents': typeof PatentsIndexRoute
  '/publications': typeof PublicationsIndexRoute
  '/app/departments/create': typeof AppDepartmentsCreateRoute
  '/app/faculties/create': typeof AppFacultiesCreateRoute
  '/app/patents/$patentId': typeof AppPatentsPatentIdRouteWithChildren
  '/app/patents/create': typeof AppPatentsCreateRoute
  '/app/profile/create': typeof AppProfileCreateRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/publications/$publicationId': typeof AppPublicationsPublicationIdRouteWithChildren
  '/app/publications/create': typeof AppPublicationsCreateRoute
  '/app/imports': typeof AppImportsIndexRoute
  '/app/patents': typeof AppPatentsIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/publications': typeof AppPublicationsIndexRoute
  '/app/patents/$patentId/edit': typeof AppPatentsPatentIdEditRoute
  '/app/publications/$publicationId/edit': typeof AppPublicationsPublicationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$profileId': typeof AuthorsProfileIdRoute
  '/patents/$patentId': typeof PatentsPatentIdRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/app/': typeof AppIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/patents/': typeof PatentsIndexRoute
  '/publications/': typeof PublicationsIndexRoute
  '/app/departments/create': typeof AppDepartmentsCreateRoute
  '/app/faculties/create': typeof AppFacultiesCreateRoute
  '/app/patents/$patentId': typeof AppPatentsPatentIdRouteWithChildren
  '/app/patents/create': typeof AppPatentsCreateRoute
  '/app/profile/create': typeof AppProfileCreateRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/publications/$publicationId': typeof AppPublicationsPublicationIdRouteWithChildren
  '/app/publications/create': typeof AppPublicationsCreateRoute
  '/app/imports/': typeof AppImportsIndexRoute
  '/app/patents/': typeof AppPatentsIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/publications/': typeof AppPublicationsIndexRoute
  '/app/patents/$patentId/edit': typeof AppPatentsPatentIdEditRoute
  '/app/publications/$publicationId/edit': typeof AppPublicationsPublicationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$profileId'
    | '/patents/$patentId'
    | '/publications/$publicationId'
    | '/app/'
    | '/authors/'
    | '/patents/'
    | '/publications/'
    | '/app/departments/create'
    | '/app/faculties/create'
    | '/app/patents/$patentId'
    | '/app/patents/create'
    | '/app/profile/create'
    | '/app/profile/edit'
    | '/app/publications/$publicationId'
    | '/app/publications/create'
    | '/app/imports/'
    | '/app/patents/'
    | '/app/profile/'
    | '/app/publications/'
    | '/app/patents/$patentId/edit'
    | '/app/publications/$publicationId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$profileId'
    | '/patents/$patentId'
    | '/publications/$publicationId'
    | '/app'
    | '/authors'
    | '/patents'
    | '/publications'
    | '/app/departments/create'
    | '/app/faculties/create'
    | '/app/patents/$patentId'
    | '/app/patents/create'
    | '/app/profile/create'
    | '/app/profile/edit'
    | '/app/publications/$publicationId'
    | '/app/publications/create'
    | '/app/imports'
    | '/app/patents'
    | '/app/profile'
    | '/app/publications'
    | '/app/patents/$patentId/edit'
    | '/app/publications/$publicationId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$profileId'
    | '/patents/$patentId'
    | '/publications/$publicationId'
    | '/app/'
    | '/authors/'
    | '/patents/'
    | '/publications/'
    | '/app/departments/create'
    | '/app/faculties/create'
    | '/app/patents/$patentId'
    | '/app/patents/create'
    | '/app/profile/create'
    | '/app/profile/edit'
    | '/app/publications/$publicationId'
    | '/app/publications/create'
    | '/app/imports/'
    | '/app/patents/'
    | '/app/profile/'
    | '/app/publications/'
    | '/app/patents/$patentId/edit'
    | '/app/publications/$publicationId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthorsProfileIdRoute: typeof AuthorsProfileIdRoute
  PatentsPatentIdRoute: typeof PatentsPatentIdRoute
  PublicationsPublicationIdRoute: typeof PublicationsPublicationIdRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  PatentsIndexRoute: typeof PatentsIndexRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$profileId': {
      id: '/authors/$profileId'
      path: '/authors/$profileId'
      fullPath: '/authors/$profileId'
      preLoaderRoute: typeof AuthorsProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patents/': {
      id: '/patents/'
      path: '/patents'
      fullPath: '/patents/'
      preLoaderRoute: typeof PatentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patents/$patentId': {
      id: '/patents/$patentId'
      path: '/patents/$patentId'
      fullPath: '/patents/$patentId'
      preLoaderRoute: typeof PatentsPatentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$publicationId': {
      id: '/publications/$publicationId'
      path: '/publications/$publicationId'
      fullPath: '/publications/$publicationId'
      preLoaderRoute: typeof PublicationsPublicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/departments/create': {
      id: '/app/departments/create'
      path: '/departments/create'
      fullPath: '/app/departments/create'
      preLoaderRoute: typeof AppDepartmentsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faculties/create': {
      id: '/app/faculties/create'
      path: '/faculties/create'
      fullPath: '/app/faculties/create'
      preLoaderRoute: typeof AppFacultiesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imports/': {
      id: '/app/imports/'
      path: '/imports'
      fullPath: '/app/imports/'
      preLoaderRoute: typeof AppImportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patents/': {
      id: '/app/patents/'
      path: '/patents'
      fullPath: '/app/patents/'
      preLoaderRoute: typeof AppPatentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patents/$patentId': {
      id: '/app/patents/$patentId'
      path: '/patents/$patentId'
      fullPath: '/app/patents/$patentId'
      preLoaderRoute: typeof AppPatentsPatentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patents/create': {
      id: '/app/patents/create'
      path: '/patents/create'
      fullPath: '/app/patents/create'
      preLoaderRoute: typeof AppPatentsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/create': {
      id: '/app/profile/create'
      path: '/profile/create'
      fullPath: '/app/profile/create'
      preLoaderRoute: typeof AppProfileCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publications/': {
      id: '/app/publications/'
      path: '/publications'
      fullPath: '/app/publications/'
      preLoaderRoute: typeof AppPublicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publications/$publicationId': {
      id: '/app/publications/$publicationId'
      path: '/publications/$publicationId'
      fullPath: '/app/publications/$publicationId'
      preLoaderRoute: typeof AppPublicationsPublicationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publications/create': {
      id: '/app/publications/create'
      path: '/publications/create'
      fullPath: '/app/publications/create'
      preLoaderRoute: typeof AppPublicationsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patents/$patentId/edit': {
      id: '/app/patents/$patentId/edit'
      path: '/edit'
      fullPath: '/app/patents/$patentId/edit'
      preLoaderRoute: typeof AppPatentsPatentIdEditRouteImport
      parentRoute: typeof AppPatentsPatentIdRoute
    }
    '/app/publications/$publicationId/edit': {
      id: '/app/publications/$publicationId/edit'
      path: '/edit'
      fullPath: '/app/publications/$publicationId/edit'
      preLoaderRoute: typeof AppPublicationsPublicationIdEditRouteImport
      parentRoute: typeof AppPublicationsPublicationIdRoute
    }
  }
}

interface AppPatentsPatentIdRouteChildren {
  AppPatentsPatentIdEditRoute: typeof AppPatentsPatentIdEditRoute
}

const AppPatentsPatentIdRouteChildren: AppPatentsPatentIdRouteChildren = {
  AppPatentsPatentIdEditRoute: AppPatentsPatentIdEditRoute,
}

const AppPatentsPatentIdRouteWithChildren =
  AppPatentsPatentIdRoute._addFileChildren(AppPatentsPatentIdRouteChildren)

interface AppPublicationsPublicationIdRouteChildren {
  AppPublicationsPublicationIdEditRoute: typeof AppPublicationsPublicationIdEditRoute
}

const AppPublicationsPublicationIdRouteChildren: AppPublicationsPublicationIdRouteChildren =
  {
    AppPublicationsPublicationIdEditRoute:
      AppPublicationsPublicationIdEditRoute,
  }

const AppPublicationsPublicationIdRouteWithChildren =
  AppPublicationsPublicationIdRoute._addFileChildren(
    AppPublicationsPublicationIdRouteChildren,
  )

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDepartmentsCreateRoute: typeof AppDepartmentsCreateRoute
  AppFacultiesCreateRoute: typeof AppFacultiesCreateRoute
  AppPatentsPatentIdRoute: typeof AppPatentsPatentIdRouteWithChildren
  AppPatentsCreateRoute: typeof AppPatentsCreateRoute
  AppProfileCreateRoute: typeof AppProfileCreateRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppPublicationsPublicationIdRoute: typeof AppPublicationsPublicationIdRouteWithChildren
  AppPublicationsCreateRoute: typeof AppPublicationsCreateRoute
  AppImportsIndexRoute: typeof AppImportsIndexRoute
  AppPatentsIndexRoute: typeof AppPatentsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppPublicationsIndexRoute: typeof AppPublicationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDepartmentsCreateRoute: AppDepartmentsCreateRoute,
  AppFacultiesCreateRoute: AppFacultiesCreateRoute,
  AppPatentsPatentIdRoute: AppPatentsPatentIdRouteWithChildren,
  AppPatentsCreateRoute: AppPatentsCreateRoute,
  AppProfileCreateRoute: AppProfileCreateRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppPublicationsPublicationIdRoute:
    AppPublicationsPublicationIdRouteWithChildren,
  AppPublicationsCreateRoute: AppPublicationsCreateRoute,
  AppImportsIndexRoute: AppImportsIndexRoute,
  AppPatentsIndexRoute: AppPatentsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppPublicationsIndexRoute: AppPublicationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthorsProfileIdRoute: AuthorsProfileIdRoute,
  PatentsPatentIdRoute: PatentsPatentIdRoute,
  PublicationsPublicationIdRoute: PublicationsPublicationIdRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  PatentsIndexRoute: PatentsIndexRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
